### ISSUE TITLE
Images | Resource Checklist

### ISSUE THREAD

**Issue by rachdaup93** [rachdaup93/SavortheFlavor#1]
### Images: ###
- [x] (10 recipe images per category)
- [ ] tablet with mobile view advertising
- [x] social media icons

**Comment by rachdaup93** [comment]
FOOD CATEGORIES (10 images each)
- [x] Breakfast
- [x] Desserts
- [x] Drinks
- [x] Pasta
- [x] Poultry
- [x] Salads
- [x] Seafood
- [x] Sides
- [x] Soups
- [x] Vegetarian

**Comment by rachdaup93** [comment]
use bootstrap social buttons instead
https://mdbootstrap.com/components/social-buttons/
